export const FACTORS = ["OBESITY", "DIABETES", "BPHIGH", "CSMOKING", "LPA", "MHLTH"]

export const DEFAULT_WEIGHTS = {
  OBESITY: 5,
  DIABETES: 5,
  BPHIGH: 5,
  CSMOKING: 5,
  LPA: 5,
  MHLTH: 5,
}
